export const Routes = [
    {
        title:"Posts",
        route:"posts"
    },
    {
        title:"Comments",
        route:"comments"
    },
    {
        title:"Albums",
        route:"albums"
    },
    {
        title:'Photos',
        route:"photos"
    },
    {
        title:'Todos',
        route:"todos"
    },
    {
        title:'Users',
        route:"users"
    }
]